[project]
name = "ort-builder"
version = "0.1.0"
description = "ONNX Runtime static library builder"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bin2c>=0.2.0",
    "onnx==1.13.1",
    "onnxruntime==1.16.3",
]
